/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import com.lowagie.text.pdf.AcroFields;
import com.lowagie.text.pdf.PdfReader;
import com.lowagie.text.pdf.PdfStamper;
import java.awt.Color;
import java.awt.FileDialog;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author RojeruSan
 */
public class Crud extends javax.swing.JFrame {

    /**
     * Creates new form Crud
     */
    public Crud() {
        initComponents();
        rsutilities.RSUtilities.setCentrarVentana(this);
        rsutilities.RSUtilities.setMoverVentana(this);
        rsutilities.RSUtilities.setOpaqueVentana(this, false);

        jScrollPane1.getViewport().setBackground(Color.white);

        //Funciones.setListar("");

        jPopupMenu1.add(menu);
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        btnEditar = new rsmaterialcomponents.RSButtonMaterialIconUno();
        btnNuevoIngreso = new rsmaterialcomponents.RSButtonMaterialIconUno();
        btnActualizar = new rsmaterialcomponents.RSButtonMaterialIconUno();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnCerrar = new rsmaterialcomponents.RSButtonIconUno();
        jLabel1 = new javax.swing.JLabel();
        rSLabelIcon1 = new rsmaterialcomponents.RSLabelIcon();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new rojerusan.RSTableMetro();
        btnNuevo = new rsmaterialcomponents.RSButtonMaterialIconUno();
        txtBuscar = new rsmaterialcomponents.RSTextFieldIconUno();
        btnImprimir1 = new rsmaterialcomponents.RSButtonMaterialIconUno();
        comboTipodeBusqueda = new org.bolivia.combo.SComboBox();
        btnGuardarArchivos = new rsmaterialcomponents.RSButtonMaterialIconUno();

        menu.setBackground(new java.awt.Color(0, 126, 51));

        btnEditar.setBackground(new java.awt.Color(0, 126, 51));
        btnEditar.setText("ACTUALIZAR DATOS");
        btnEditar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnNuevoIngreso.setBackground(new java.awt.Color(0, 126, 51));
        btnNuevoIngreso.setText("NUEVO INGRESO");
        btnNuevoIngreso.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.NOTE_ADD);
        btnNuevoIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoIngresoActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(0, 126, 51));
        btnActualizar.setText("VER REGISTRO");
        btnActualizar.setActionCommand("ACTUALIZAR DATOS");
        btnActualizar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PAGEVIEW);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPopupMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPopupMenu1.setMaximumSize(new java.awt.Dimension(9, 9));
        jPopupMenu1.setMinimumSize(new java.awt.Dimension(9, 9));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 126, 51));

        btnCerrar.setBackground(new java.awt.Color(0, 126, 51));
        btnCerrar.setToolTipText("CERRAR");
        btnCerrar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("ADMISIONES - Hospital Regional de Huehuetenango \"Dr. Jorge Vides Molina\"");

        rSLabelIcon1.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LANGUAGE);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSLabelIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1160, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(rSLabelIcon1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 126, 51), 2));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "HISTORIA CLINICA No.", "NOMBRES", "APELLIDO 1", "APELLIDO 2", "NOMBRE DEL PADRE", "NOMBRE DE LA MADRE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setAltoHead(30);
        tabla.setColorBackgoundHead(new java.awt.Color(0, 126, 51));
        tabla.setColorFilasForeground1(new java.awt.Color(0, 126, 51));
        tabla.setColorFilasForeground2(new java.awt.Color(0, 126, 51));
        tabla.setColorSelBackgound(new java.awt.Color(0, 126, 51));
        tabla.setComponentPopupMenu(jPopupMenu1);
        tabla.setFuenteHead(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabla.setGrosorBordeFilas(0);
        tabla.setGrosorBordeHead(0);
        tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla);

        btnNuevo.setBackground(new java.awt.Color(0, 126, 51));
        btnNuevo.setText("NUEVO REGISTRO");
        btnNuevo.setToolTipText("REGISTRAR USUARIO");
        btnNuevo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON_ADD);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        txtBuscar.setForeground(new java.awt.Color(0, 126, 51));
        txtBuscar.setBorderColor(new java.awt.Color(0, 126, 51));
        txtBuscar.setColorIcon(new java.awt.Color(0, 126, 51));
        txtBuscar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        txtBuscar.setPlaceholder("BUSCAR...");
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        btnImprimir1.setBackground(new java.awt.Color(0, 126, 51));
        btnImprimir1.setText("INFORME DE NACIMIENTO");
        btnImprimir1.setToolTipText("GENERAR INFORME DE NACIMIENTO");
        btnImprimir1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PREGNANT_WOMAN);
        btnImprimir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir1ActionPerformed(evt);
            }
        });

        comboTipodeBusqueda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No. Historia Clinica", "Nombre Completo", "Nombre del Padre", "Nombre de la Madre" }));

        btnGuardarArchivos.setBackground(new java.awt.Color(0, 126, 51));
        btnGuardarArchivos.setText("GUARDAR KOIKA, EMER, COEX");
        btnGuardarArchivos.setToolTipText("GUARDA CUALQUIER ARCHIVO DE CUALQUIER SERVICIO (KOICA, EMER Y COEX)");
        btnGuardarArchivos.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        btnGuardarArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarArchivosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImprimir1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboTipodeBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTipodeBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarArchivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        rSPanelShadow1.add(jPanel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSPanelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        Formulario_Registro f = new Formulario_Registro(this, true);
 
        f.setVisible(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int fila = tabla.getSelectedRow();

        Formulario_Update f = new Formulario_Update(this, true);
        f.txtNombre.setText(tabla.getValueAt(fila, 1).toString());
        f.txtUsuario.setText(tabla.getValueAt(fila, 2).toString());
        f.txtPass.setText(tabla.getValueAt(fila, 3).toString());
        f.lblID.setText(tabla.getValueAt(fila, 0).toString());
        f.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnNuevoIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoIngresoActionPerformed
        int fila = tabla.getSelectedRow();

        Sentencias s = new Sentencias();
        s.setId(tabla.getValueAt(fila, 0).toString());

        if (JOptionPane.showConfirmDialog(this, "¿ELIMINAR REGISTRO?", "",
                JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            if (Funciones.isDelete(s)) {
                //Funciones.setListar("");
                JOptionPane.showMessageDialog(this, "REGISTRO ELIMINADO CON ÉXITO.", "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "ERROR AL INTENTAR ELIMINAR EL REGISTRO.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnNuevoIngresoActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        int tipobusqueda = comboTipodeBusqueda.getSelectedIndex();
        Funciones.setListar(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnImprimir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir1ActionPerformed
        // TODO add your handling code here:
        //Funciones.setListar(this.txtBuscar.getText());
        
    }//GEN-LAST:event_btnImprimir1ActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnGuardarArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarArchivosActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        //String rutatotal="";
        //FileDialog dialogoArchivo;
        //dialogoArchivo = new FileDialog(this, "Lista de Archivos desde Frame",FileDialog.LOAD);
        //dialogoArchivo.setVisible(true);
        //if(dialogoArchivo.getFile()!=null)
        //{ 
        //    String directorio = dialogoArchivo.getDirectory();
        //    String nombreArchivo =dialogoArchivo.getFile(); 
        //    rutatotal = directorio + nombreArchivo;
        //}
        //else
        //{
          //  System.out.println("No Seleccionó Archivo");
        //}
        //System.out.println(rutatotal);
       
        try {
 	//Leemos el pdf que nos servirá como plantilla
        for(int i=1;i<=30000;i++)
        {

        PdfReader reader = new PdfReader("C:\\COEX\\  ("+i+").pdf");
        
        
	// Creamos el pdf de salida
        PdfStamper stamp = new PdfStamper(reader, new
       			FileOutputStream("C:\\COEX\\IMPRIMIRADMISION.pdf"));
            AcroFields form1 = reader.getAcroFields();
            Sentencias s = new Sentencias();
            //txtaux.setText(form1.getField("Historia Clinica"));
            s.setId("1");
            s.setHistoriaClinica(form1.getField("Registro"));
            s.setApellido1(form1.getField("Apellido 1"));
            s.setApellido2(form1.getField("Apellido 2"));
            s.setApellido3(form1.getField("Apellido 3"));
            s.setNombres(form1.getField("Nombres"));
            s.setSexo(form1.getField("Sexo"));
            
            if(form1.getField("Años")==""){
                s.setEdad(null);
            }
            else 
            {
                s.setEdad(form1.getField("Años"));
            }
            if(form1.getField("Meses")==""){
                s.setEdadmeses(null);
            }
            else 
            {
                s.setEdadmeses(form1.getField("Meses"));
            }
            if(form1.getField("Días")==""){
                s.setEdaddias(null);
            }
            else 
            {
                s.setEdaddias(form1.getField("Días"));
            }
            s.setConyuge(form1.getField("Cónyuge"));
            s.setFechanacimiento(form1.getField("Fecha Nacimiento"));
            s.setLugardenacimiento(form1.getField("Lugar Nacimiento"));
            s.setNacionalidad(form1.getField("Nacionalidad"));
            s.setDPI(form1.getField("Identificación"));
            s.setEstadocivil(form1.getField("Estado Civil"));
            s.setGrupoetnico(form1.getField("Grupo Étnico"));
            s.setReligion(form1.getField("Religión"));
            s.setAfiliadoaligss(form1.getField("Afiliado al IGSS"));
            s.setNumerotelefono(form1.getField("Teléfono"));
            s.setEscolaridad(form1.getField("Escolaridad"));
            s.setProfesion(form1.getField("Profesión Oficio Ocupación"));
            s.setLugardetrabajo(form1.getField("Lugar de Trabajo"));
            s.setResidencia(form1.getField("Dirección"));
            s.setNombrepadre(form1.getField("Nombre del padre"));
            s.setPadrevivo(form1.getField("Padre"));
            s.setNombremadre(form1.getField("Nombre de la madre"));
            s.setMadreviva(form1.getField("Madre"));
            s.setEncargado(form1.getField("En urgencia avisar a"));
            s.setDireccionencargado(form1.getField("Dirección"));
            s.setServiciodeingreso(form1.getField("Servicio"));
            if(form1.getField("Otra especialidad")==""){
                s.setOtraespecialidad(null);
            }
            else 
            {
               s.setOtraespecialidad(form1.getField("Otra especialidad"));
            }
            s.setFecha(form1.getField("Fecha"));
            s.setHora(form1.getField("Hora"));
            s.setMedico(form1.getField("Médico"));
            s.setAdmitidopor(form1.getField("Documenta"));
            s.setIngresa(form1.getField("Ingresa"));
            if(form1.getField("Ingresa a")==""){
                s.setIngresaa(null);
            }
            else 
            {
               s.setIngresaa(form1.getField("Ingresa a"));
            }
            
    
            
            if (Funciones.isRegister(s)) {
                System.out.println("REGISTRADO. " + i );//JOptionPane.showMessageDialog(this, "EL REGISTRO  "+form1.getField("Historia Clinica") +"  FUE GUARDADO CON ÉXITO.", "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
            } else {
                System.out.println("ERROR AL INTENTAR REGISTRAR.  " + i + "  HISTORIA CLINICA:  "+ form1.getField("Registro"));
                //JOptionPane.showMessageDialog(this, "ERROR AL INTENTAR REGISTRAR." + i, "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            stamp.setFormFlattening(true);
            stamp.close();
        }
        
        
 
	}catch (Exception e) {
		e.printStackTrace();
	}
    }//GEN-LAST:event_btnGuardarArchivosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crud().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsmaterialcomponents.RSButtonMaterialIconUno btnActualizar;
    private rsmaterialcomponents.RSButtonIconUno btnCerrar;
    private rsmaterialcomponents.RSButtonMaterialIconUno btnEditar;
    private rsmaterialcomponents.RSButtonMaterialIconUno btnGuardarArchivos;
    private rsmaterialcomponents.RSButtonMaterialIconUno btnImprimir1;
    private rsmaterialcomponents.RSButtonMaterialIconUno btnNuevo;
    private rsmaterialcomponents.RSButtonMaterialIconUno btnNuevoIngreso;
    private org.bolivia.combo.SComboBox comboTipodeBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menu;
    private rsmaterialcomponents.RSLabelIcon rSLabelIcon1;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    public static rojerusan.RSTableMetro tabla;
    private rsmaterialcomponents.RSTextFieldIconUno txtBuscar;
    // End of variables declaration//GEN-END:variables
}
