/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;


import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author RojeruSan
 */
public class Formulario_Registro extends javax.swing.JDialog {

    /**
     * Creates new form Formulario
     */
    public Formulario_Registro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
  
        rsutilities.RSUtilities.setCentrarVentana(this);
        rsutilities.RSUtilities.setMoverVentana(this);
        rsutilities.RSUtilities.setOpaqueVentana(this, false);
        
        setClean();
    }

    public void setClean(){
        this.txtNombre.setText("");
        this.txtHistoriaClinica.setText("");
       // this.txtPass.setText("");
        
        this.lblError.setText("");
        this.lblID.setText(Funciones.extraerIDMax());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnCerrar = new rsmaterialcomponents.RSButtonIconUno();
        txtNombre = new rsmaterialcomponents.RSTextFieldIconUno();
        txtHistoriaClinica = new rsmaterialcomponents.RSTextFieldIconUno();
        lblID = new javax.swing.JLabel();
        txtApellido1 = new rsmaterialcomponents.RSTextFieldIconUno();
        txtApellido2 = new rsmaterialcomponents.RSTextFieldIconUno();
        txtNombrepadre = new rsmaterialcomponents.RSTextFieldIconUno();
        txtNombremadre = new rsmaterialcomponents.RSTextFieldIconUno();
        txtEncargado = new rsmaterialcomponents.RSTextFieldIconUno();
        txtFechaNacimiento = new rsmaterialcomponents.RSTextFieldIconUno();
        txtdireccion = new rsmaterialcomponents.RSTextFieldIconUno();
        txtDireccionEncargado = new rsmaterialcomponents.RSTextFieldIconUno();
        txtEdad = new rsmaterialcomponents.RSTextFieldIconUno();
        txtLugardondetrabaja = new rsmaterialcomponents.RSTextFieldIconUno();
        txtNacionalidad = new rsmaterialcomponents.RSTextFieldIconUno();
        txtTelefono = new rsmaterialcomponents.RSTextFieldIconUno();
        txtprofesion = new rsmaterialcomponents.RSTextFieldIconUno();
        txtConyuge = new rsmaterialcomponents.RSTextFieldIconUno();
        txtDPI = new rsmaterialcomponents.RSTextFieldIconUno();
        comboSexo = new org.bolivia.combo.SComboBox();
        comboEstadoCivil = new org.bolivia.combo.SComboBox();
        comboGrupoEtnico = new org.bolivia.combo.SComboBox();
        comboReligion = new org.bolivia.combo.SComboBox();
        comboAfliliadoIgss = new org.bolivia.combo.SComboBox();
        comboEscolaridad = new org.bolivia.combo.SComboBox();
        comboDepartamento = new org.bolivia.combo.SComboBox();
        comboMunicipio = new org.bolivia.combo.SComboBox();
        comboMadreViva = new org.bolivia.combo.SComboBox();
        comboPadreVivo = new org.bolivia.combo.SComboBox();
        comboClasedeAdmision = new org.bolivia.combo.SComboBox();
        comboServicioqueingreso = new org.bolivia.combo.SComboBox();
        txtfecha = new rsmaterialcomponents.RSTextFieldIconUno();
        txthora = new rsmaterialcomponents.RSTextFieldIconUno();
        comboMedico = new org.bolivia.combo.SComboBox();
        comboAdmisionechapor = new org.bolivia.combo.SComboBox();
        combotipodeadmision = new org.bolivia.combo.SComboBox();
        lblError = new javax.swing.JLabel();
        btnImprimir2 = new rsmaterialcomponents.RSButtonMaterialIconUno();
        btnImprimir3 = new rsmaterialcomponents.RSButtonMaterialIconUno();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 610));

        jPanel2.setBackground(new java.awt.Color(0, 126, 51));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Nuevo Ingreso");

        btnCerrar.setBackground(new java.awt.Color(0, 126, 51));
        btnCerrar.setToolTipText("CERRAR");
        btnCerrar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        txtNombre.setForeground(new java.awt.Color(0, 126, 51));
        txtNombre.setBorderColor(new java.awt.Color(0, 126, 51));
        txtNombre.setColorIcon(new java.awt.Color(0, 126, 51));
        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNombre.setPlaceholder("NOMBRES");
        txtNombre.setSelectionColor(new java.awt.Color(0, 126, 51));

        txtHistoriaClinica.setForeground(new java.awt.Color(0, 126, 51));
        txtHistoriaClinica.setBorderColor(new java.awt.Color(0, 126, 51));
        txtHistoriaClinica.setColorIcon(new java.awt.Color(0, 126, 51));
        txtHistoriaClinica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtHistoriaClinica.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        txtHistoriaClinica.setPlaceholder("HISTORIA CLINICA No.");
        txtHistoriaClinica.setSelectionColor(new java.awt.Color(0, 126, 51));

        lblID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblID.setText("id");

        txtApellido1.setForeground(new java.awt.Color(0, 126, 51));
        txtApellido1.setBorderColor(new java.awt.Color(0, 126, 51));
        txtApellido1.setColorIcon(new java.awt.Color(0, 126, 51));
        txtApellido1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtApellido1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_CIRCLE);
        txtApellido1.setPlaceholder("APELLIDO 1");
        txtApellido1.setSelectionColor(new java.awt.Color(0, 126, 51));
        txtApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido1ActionPerformed(evt);
            }
        });

        txtApellido2.setForeground(new java.awt.Color(0, 126, 51));
        txtApellido2.setBorderColor(new java.awt.Color(0, 126, 51));
        txtApellido2.setColorIcon(new java.awt.Color(0, 126, 51));
        txtApellido2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtApellido2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_CIRCLE);
        txtApellido2.setPlaceholder("APELLIDO 2");
        txtApellido2.setSelectionColor(new java.awt.Color(0, 126, 51));

        txtNombrepadre.setForeground(new java.awt.Color(0, 126, 51));
        txtNombrepadre.setBorderColor(new java.awt.Color(0, 126, 51));
        txtNombrepadre.setColorIcon(new java.awt.Color(0, 0, 204));
        txtNombrepadre.setPlaceholder("NOMBRE DEL PADRE");
        txtNombrepadre.setSelectionColor(new java.awt.Color(0, 126, 51));

        txtNombremadre.setForeground(new java.awt.Color(0, 126, 51));
        txtNombremadre.setBorderColor(new java.awt.Color(0, 126, 51));
        txtNombremadre.setColorIcon(new java.awt.Color(255, 102, 255));
        txtNombremadre.setPlaceholder("NOMBRE DE LA MADRE");
        txtNombremadre.setSelectionColor(new java.awt.Color(0, 126, 51));
        txtNombremadre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombremadreFocusLost(evt);
            }
        });
        txtNombremadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombremadreActionPerformed(evt);
            }
        });
        txtNombremadre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombremadreKeyPressed(evt);
            }
        });

        txtEncargado.setForeground(new java.awt.Color(0, 126, 51));
        txtEncargado.setBorderColor(new java.awt.Color(0, 126, 51));
        txtEncargado.setColorIcon(new java.awt.Color(0, 126, 51));
        txtEncargado.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.WARNING);
        txtEncargado.setPlaceholder("EN CASO DE URGENCIA AVISAR A:");
        txtEncargado.setSelectionColor(new java.awt.Color(0, 126, 51));

        txtFechaNacimiento.setForeground(new java.awt.Color(0, 126, 51));
        txtFechaNacimiento.setBorderColor(new java.awt.Color(0, 126, 51));
        txtFechaNacimiento.setColorIcon(new java.awt.Color(0, 126, 51));
        txtFechaNacimiento.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DATE_RANGE);
        txtFechaNacimiento.setPlaceholder("FECHA DE NACIMIENTO");
        txtFechaNacimiento.setSelectionColor(new java.awt.Color(0, 126, 51));
        txtFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacimientoActionPerformed(evt);
            }
        });

        txtdireccion.setForeground(new java.awt.Color(0, 126, 51));
        txtdireccion.setBorderColor(new java.awt.Color(0, 126, 51));
        txtdireccion.setColorIcon(new java.awt.Color(0, 126, 51));
        txtdireccion.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);
        txtdireccion.setPlaceholder("DIRECCIÓN");
        txtdireccion.setSelectionColor(new java.awt.Color(0, 126, 51));
        txtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionActionPerformed(evt);
            }
        });

        txtDireccionEncargado.setForeground(new java.awt.Color(0, 126, 51));
        txtDireccionEncargado.setBorderColor(new java.awt.Color(0, 126, 51));
        txtDireccionEncargado.setColorIcon(new java.awt.Color(0, 126, 51));
        txtDireccionEncargado.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);
        txtDireccionEncargado.setPlaceholder("DIRECCIÓN");
        txtDireccionEncargado.setSelectionColor(new java.awt.Color(0, 126, 51));
        txtDireccionEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionEncargadoActionPerformed(evt);
            }
        });

        txtEdad.setForeground(new java.awt.Color(0, 126, 51));
        txtEdad.setBorderColor(new java.awt.Color(0, 126, 51));
        txtEdad.setColorIcon(new java.awt.Color(0, 126, 51));
        txtEdad.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_CIRCLE);
        txtEdad.setPlaceholder("EDAD");
        txtEdad.setSelectionColor(new java.awt.Color(0, 126, 51));
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });

        txtLugardondetrabaja.setForeground(new java.awt.Color(0, 126, 51));
        txtLugardondetrabaja.setBorderColor(new java.awt.Color(0, 126, 51));
        txtLugardondetrabaja.setColorIcon(new java.awt.Color(0, 126, 51));
        txtLugardondetrabaja.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_CIRCLE);
        txtLugardondetrabaja.setPlaceholder("LUGAR DONDE TRABAJA");
        txtLugardondetrabaja.setSelectionColor(new java.awt.Color(0, 126, 51));
        txtLugardondetrabaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLugardondetrabajaActionPerformed(evt);
            }
        });

        txtNacionalidad.setForeground(new java.awt.Color(0, 126, 51));
        txtNacionalidad.setBorderColor(new java.awt.Color(0, 126, 51));
        txtNacionalidad.setColorIcon(new java.awt.Color(0, 126, 51));
        txtNacionalidad.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PUBLIC);
        txtNacionalidad.setInheritsPopupMenu(true);
        txtNacionalidad.setPlaceholder("NACIONALIDAD");
        txtNacionalidad.setSelectionColor(new java.awt.Color(0, 126, 51));
        txtNacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNacionalidadActionPerformed(evt);
            }
        });

        txtTelefono.setForeground(new java.awt.Color(0, 126, 51));
        txtTelefono.setBorderColor(new java.awt.Color(0, 126, 51));
        txtTelefono.setColorIcon(new java.awt.Color(0, 126, 51));
        txtTelefono.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PHONE);
        txtTelefono.setPlaceholder("TELÉFONO");
        txtTelefono.setSelectionColor(new java.awt.Color(0, 126, 51));
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        txtprofesion.setForeground(new java.awt.Color(0, 126, 51));
        txtprofesion.setBorderColor(new java.awt.Color(0, 126, 51));
        txtprofesion.setColorIcon(new java.awt.Color(0, 126, 51));
        txtprofesion.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.WORK);
        txtprofesion.setPlaceholder("PROFESIÓN/OCUPACIÓN/OFICIO");
        txtprofesion.setSelectionColor(new java.awt.Color(0, 126, 51));
        txtprofesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprofesionActionPerformed(evt);
            }
        });

        txtConyuge.setForeground(new java.awt.Color(0, 126, 51));
        txtConyuge.setBorderColor(new java.awt.Color(0, 126, 51));
        txtConyuge.setColorIcon(new java.awt.Color(0, 126, 51));
        txtConyuge.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_CIRCLE);
        txtConyuge.setPlaceholder("CONYUGGUE");
        txtConyuge.setSelectionColor(new java.awt.Color(0, 126, 51));
        txtConyuge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConyugeActionPerformed(evt);
            }
        });

        txtDPI.setForeground(new java.awt.Color(0, 126, 51));
        txtDPI.setBorderColor(new java.awt.Color(0, 126, 51));
        txtDPI.setColorIcon(new java.awt.Color(0, 126, 51));
        txtDPI.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_BOX);
        txtDPI.setPlaceholder("DPI");
        txtDPI.setSelectionColor(new java.awt.Color(0, 126, 51));
        txtDPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDPIActionPerformed(evt);
            }
        });

        comboSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEXO", "MASCULINO", "FEMENINO" }));
        comboSexo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        comboEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ESTADO CIVIL", "CASADO", "SOLTERO" }));
        comboEstadoCivil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        comboGrupoEtnico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GRUPO ÉTNICO", "MAYA", "GARIFUNA" }));
        comboGrupoEtnico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboGrupoEtnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGrupoEtnicoActionPerformed(evt);
            }
        });

        comboReligion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RELIGIÓN", "CATÓLICO", "EVANGÉLICO" }));
        comboReligion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboReligion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboReligionActionPerformed(evt);
            }
        });

        comboAfliliadoIgss.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AFILIADO AL IGSS?", "SI", "NO" }));
        comboAfliliadoIgss.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboAfliliadoIgss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAfliliadoIgssActionPerformed(evt);
            }
        });

        comboEscolaridad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ESCOLARIDAD", "PRIMARIA", "PREPRIMARIA" }));
        comboEscolaridad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboEscolaridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEscolaridadActionPerformed(evt);
            }
        });

        comboDepartamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DEPARTAMENTO", "HUEHUETENANGO", "CHIANTLA" }));
        comboDepartamento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDepartamentoActionPerformed(evt);
            }
        });

        comboMunicipio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MUNICIPIO" }));
        comboMunicipio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMunicipioActionPerformed(evt);
            }
        });

        comboMadreViva.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VIVA?", "SI", "NO" }));
        comboMadreViva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        comboPadreVivo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VIVO?", "SI", "NO" }));
        comboPadreVivo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        comboClasedeAdmision.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CLASE DE ADMISIÓN", "CONSULTA EXTERNA", "URGENCIAS", "DIRECTAS (A UCIN)" }));
        comboClasedeAdmision.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboClasedeAdmision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboClasedeAdmisionActionPerformed(evt);
            }
        });

        comboServicioqueingreso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SERVICIO DE INGRESO" }));
        comboServicioqueingreso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboServicioqueingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboServicioqueingresoActionPerformed(evt);
            }
        });

        txtfecha.setForeground(new java.awt.Color(0, 126, 51));
        txtfecha.setBorderColor(new java.awt.Color(0, 126, 51));
        txtfecha.setColorIcon(new java.awt.Color(0, 126, 51));
        txtfecha.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);
        txtfecha.setPlaceholder("FECHA");
        txtfecha.setSelectionColor(new java.awt.Color(0, 126, 51));
        txtfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechaActionPerformed(evt);
            }
        });

        txthora.setForeground(new java.awt.Color(0, 126, 51));
        txthora.setBorderColor(new java.awt.Color(0, 126, 51));
        txthora.setColorIcon(new java.awt.Color(0, 126, 51));
        txthora.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);
        txthora.setPlaceholder("HORA");
        txthora.setSelectionColor(new java.awt.Color(0, 126, 51));
        txthora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthoraActionPerformed(evt);
            }
        });

        comboMedico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MEDICO QUE ORDENO EL INGRESO" }));
        comboMedico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMedicoActionPerformed(evt);
            }
        });

        comboAdmisionechapor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ADMISIÓN HECHA POR" }));
        comboAdmisionechapor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboAdmisionechapor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAdmisionechaporActionPerformed(evt);
            }
        });

        combotipodeadmision.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TIPO DE ADMISIÓN" }));
        combotipodeadmision.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combotipodeadmision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combotipodeadmisionActionPerformed(evt);
            }
        });

        lblError.setText("jLabel1");

        btnImprimir2.setBackground(new java.awt.Color(0, 126, 51));
        btnImprimir2.setText("GUARDAR EN BD");
        btnImprimir2.setToolTipText("REGISTRAR USUARIO");
        btnImprimir2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        btnImprimir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir2ActionPerformed(evt);
            }
        });

        btnImprimir3.setBackground(new java.awt.Color(0, 126, 51));
        btnImprimir3.setText("GUARDAR EN BD");
        btnImprimir3.setToolTipText("REGISTRAR USUARIO");
        btnImprimir3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        btnImprimir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombremadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDireccionEncargado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(comboClasedeAdmision, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboServicioqueingreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(comboMadreViva, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNombrepadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboPadreVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(comboSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtHistoriaClinica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtApellido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtApellido2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtConyuge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDPI, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboGrupoEtnico, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtprofesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboReligion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txthora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblError))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLugardondetrabaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboAfliliadoIgss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboAdmisionechapor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(btnImprimir3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnImprimir2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(comboDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(comboEscolaridad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEncargado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(combotipodeadmision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(16, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHistoriaClinica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConyuge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboGrupoEtnico, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboAfliliadoIgss, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEscolaridad, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprofesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLugardondetrabaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombremadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMadreViva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombrepadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPadreVivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDireccionEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboClasedeAdmision, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboServicioqueingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboAdmisionechapor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combotipodeadmision, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblError)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnImprimir2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnImprimir3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        rSPanelShadow1.add(jPanel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rSPanelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rSPanelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combotipodeadmisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combotipodeadmisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combotipodeadmisionActionPerformed

    private void comboAdmisionechaporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAdmisionechaporActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAdmisionechaporActionPerformed

    private void comboMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMedicoActionPerformed

    private void txthoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthoraActionPerformed

    private void txtfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechaActionPerformed

    private void comboServicioqueingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboServicioqueingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboServicioqueingresoActionPerformed

    private void comboClasedeAdmisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboClasedeAdmisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboClasedeAdmisionActionPerformed

    private void comboMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMunicipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMunicipioActionPerformed

    private void comboDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDepartamentoActionPerformed

    private void comboEscolaridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEscolaridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEscolaridadActionPerformed

    private void comboAfliliadoIgssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAfliliadoIgssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAfliliadoIgssActionPerformed

    private void comboReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboReligionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboReligionActionPerformed

    private void comboGrupoEtnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGrupoEtnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboGrupoEtnicoActionPerformed

    private void txtDPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDPIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDPIActionPerformed

    private void txtConyugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConyugeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConyugeActionPerformed

    private void txtprofesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprofesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprofesionActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtNacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNacionalidadActionPerformed

    private void txtLugardondetrabajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLugardondetrabajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLugardondetrabajaActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtDireccionEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionEncargadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionEncargadoActionPerformed

    private void txtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionActionPerformed

    private void txtFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacimientoActionPerformed

    private void txtNombremadreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombremadreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombremadreKeyPressed

    private void txtNombremadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombremadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombremadreActionPerformed

    private void txtNombremadreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombremadreFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombremadreFocusLost

    private void txtApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido1ActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnImprimir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir2ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnImprimir2ActionPerformed

    private void btnImprimir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimir3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Formulario_Registro dialog = new Formulario_Registro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsmaterialcomponents.RSButtonIconUno btnCerrar;
    private rsmaterialcomponents.RSButtonMaterialIconUno btnImprimir2;
    private rsmaterialcomponents.RSButtonMaterialIconUno btnImprimir3;
    private org.bolivia.combo.SComboBox comboAdmisionechapor;
    private org.bolivia.combo.SComboBox comboAfliliadoIgss;
    private org.bolivia.combo.SComboBox comboClasedeAdmision;
    private org.bolivia.combo.SComboBox comboDepartamento;
    private org.bolivia.combo.SComboBox comboEscolaridad;
    private org.bolivia.combo.SComboBox comboEstadoCivil;
    private org.bolivia.combo.SComboBox comboGrupoEtnico;
    private org.bolivia.combo.SComboBox comboMadreViva;
    private org.bolivia.combo.SComboBox comboMedico;
    private org.bolivia.combo.SComboBox comboMunicipio;
    private org.bolivia.combo.SComboBox comboPadreVivo;
    private org.bolivia.combo.SComboBox comboReligion;
    private org.bolivia.combo.SComboBox comboServicioqueingreso;
    private org.bolivia.combo.SComboBox comboSexo;
    private org.bolivia.combo.SComboBox combotipodeadmision;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblTitulo;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private rsmaterialcomponents.RSTextFieldIconUno txtApellido1;
    private rsmaterialcomponents.RSTextFieldIconUno txtApellido2;
    private rsmaterialcomponents.RSTextFieldIconUno txtConyuge;
    private rsmaterialcomponents.RSTextFieldIconUno txtDPI;
    private rsmaterialcomponents.RSTextFieldIconUno txtDireccionEncargado;
    private rsmaterialcomponents.RSTextFieldIconUno txtEdad;
    private rsmaterialcomponents.RSTextFieldIconUno txtEncargado;
    private rsmaterialcomponents.RSTextFieldIconUno txtFechaNacimiento;
    private rsmaterialcomponents.RSTextFieldIconUno txtHistoriaClinica;
    private rsmaterialcomponents.RSTextFieldIconUno txtLugardondetrabaja;
    private rsmaterialcomponents.RSTextFieldIconUno txtNacionalidad;
    private rsmaterialcomponents.RSTextFieldIconUno txtNombre;
    private rsmaterialcomponents.RSTextFieldIconUno txtNombremadre;
    private rsmaterialcomponents.RSTextFieldIconUno txtNombrepadre;
    private rsmaterialcomponents.RSTextFieldIconUno txtTelefono;
    private rsmaterialcomponents.RSTextFieldIconUno txtdireccion;
    private rsmaterialcomponents.RSTextFieldIconUno txtfecha;
    private rsmaterialcomponents.RSTextFieldIconUno txthora;
    private rsmaterialcomponents.RSTextFieldIconUno txtprofesion;
    // End of variables declaration//GEN-END:variables

    void setExtendedState(int MAXIMIZED_BOTH) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
